#!/bin/sh
set -eu

if [ -n "${APP_ENV_FILE:-}" ] && [ -f "${APP_ENV_FILE}" ]; then
  set -a
  # shellcheck disable=SC1090
  . "${APP_ENV_FILE}"
  set +a
fi

map_prefixed_env() {
  prefixed_name="$1"
  target_name="$2"
  eval "prefixed_value=\${$prefixed_name:-}"
  eval "target_value=\${$target_name:-}"
  if [ -n "${prefixed_value}" ] && [ -z "${target_value}" ]; then
    export "${target_name}=${prefixed_value}"
  fi
}

map_prefixed_env APP_QUESTION_JSON_DIR QUESTION_JSON_DIR
map_prefixed_env APP_DATABASE_URL DATABASE_URL
map_prefixed_env APP_BOOTSTRAP_SCHEMA BOOTSTRAP_SCHEMA
map_prefixed_env APP_RUN_DB_MIGRATIONS RUN_DB_MIGRATIONS
map_prefixed_env APP_MATERIAL_DIR MATERIAL_DIR
map_prefixed_env APP_ADMIN_API_KEY ADMIN_API_KEY
map_prefixed_env APP_CORS_ORIGINS CORS_ORIGINS
map_prefixed_env APP_AUTH_TOKEN_TTL_HOURS AUTH_TOKEN_TTL_HOURS
map_prefixed_env APP_AUTH_TOKEN_BYTES AUTH_TOKEN_BYTES
map_prefixed_env APP_RATE_LIMIT_ENABLED RATE_LIMIT_ENABLED
map_prefixed_env APP_RATE_LIMIT_PUBLIC_REQUESTS RATE_LIMIT_PUBLIC_REQUESTS
map_prefixed_env APP_RATE_LIMIT_PUBLIC_WINDOW_SECONDS RATE_LIMIT_PUBLIC_WINDOW_SECONDS
map_prefixed_env APP_RATE_LIMIT_AUTH_REQUESTS RATE_LIMIT_AUTH_REQUESTS
map_prefixed_env APP_RATE_LIMIT_ADMIN_REQUESTS RATE_LIMIT_ADMIN_REQUESTS
map_prefixed_env APP_RATE_LIMIT_CACHE_SIZE RATE_LIMIT_CACHE_SIZE
map_prefixed_env APP_GEMINI_ENABLE GEMINI_ENABLE
map_prefixed_env APP_GEMINI_API_KEY GEMINI_API_KEY
map_prefixed_env APP_GEMINI_MODEL GEMINI_MODEL
map_prefixed_env APP_GEMINI_TIMEOUT_SECONDS GEMINI_TIMEOUT_SECONDS
map_prefixed_env APP_GEMINI_TEMPERATURE GEMINI_TEMPERATURE
map_prefixed_env APP_GEMINI_MAX_OUTPUT_TOKENS GEMINI_MAX_OUTPUT_TOKENS
map_prefixed_env APP_GEMINI_SYSTEM_PROMPT GEMINI_SYSTEM_PROMPT
map_prefixed_env APP_GEMINI_MIN_RESPONSE_CHARS GEMINI_MIN_RESPONSE_CHARS
map_prefixed_env APP_GEMINI_RETRY_ON_SHORT GEMINI_RETRY_ON_SHORT
map_prefixed_env APP_GEMINI_CANDIDATE_COUNT GEMINI_CANDIDATE_COUNT

: "${QUESTION_JSON_DIR:=/questions}"
: "${DATABASE_URL:=sqlite:////data/securityplus.db}"
: "${BOOTSTRAP_SCHEMA:=true}"
: "${RUN_DB_MIGRATIONS:=false}"
: "${MATERIAL_DIR:=/app/material}"
: "${AUTH_TOKEN_TTL_HOURS:=168}"
: "${AUTH_TOKEN_BYTES:=32}"
: "${RATE_LIMIT_ENABLED:=true}"
: "${RATE_LIMIT_PUBLIC_REQUESTS:=180}"
: "${RATE_LIMIT_PUBLIC_WINDOW_SECONDS:=60}"
: "${RATE_LIMIT_AUTH_REQUESTS:=40}"
: "${RATE_LIMIT_ADMIN_REQUESTS:=60}"
: "${RATE_LIMIT_CACHE_SIZE:=50000}"
: "${CORS_ORIGINS:=http://127.0.0.1:8000,http://localhost:8000,http://127.0.0.1:3000,http://localhost:3000}"
: "${GEMINI_ENABLE:=true}"
: "${GEMINI_MODEL:=gemini-1.5-flash}"
: "${GEMINI_TIMEOUT_SECONDS:=20}"
: "${GEMINI_TEMPERATURE:=0.2}"
: "${GEMINI_MAX_OUTPUT_TOKENS:=400}"
: "${GEMINI_MIN_RESPONSE_CHARS:=220}"
: "${GEMINI_RETRY_ON_SHORT:=true}"
: "${GEMINI_CANDIDATE_COUNT:=1}"

export QUESTION_JSON_DIR
export DATABASE_URL
export BOOTSTRAP_SCHEMA
export RUN_DB_MIGRATIONS
export MATERIAL_DIR
export AUTH_TOKEN_TTL_HOURS
export AUTH_TOKEN_BYTES
export RATE_LIMIT_ENABLED
export RATE_LIMIT_PUBLIC_REQUESTS
export RATE_LIMIT_PUBLIC_WINDOW_SECONDS
export RATE_LIMIT_AUTH_REQUESTS
export RATE_LIMIT_ADMIN_REQUESTS
export RATE_LIMIT_CACHE_SIZE
export CORS_ORIGINS
export GEMINI_ENABLE
export GEMINI_MODEL
export GEMINI_TIMEOUT_SECONDS
export GEMINI_TEMPERATURE
export GEMINI_MAX_OUTPUT_TOKENS
export GEMINI_MIN_RESPONSE_CHARS
export GEMINI_RETRY_ON_SHORT
export GEMINI_CANDIDATE_COUNT

if [ "${RUN_DB_MIGRATIONS}" = "true" ] || [ "${RUN_DB_MIGRATIONS}" = "1" ]; then
  alembic -c /app/alembic.ini upgrade head
fi

exec "$@"
