#!/bin/sh
set -eu

if [ -n "${APP_ENV_FILE:-}" ] && [ -f "${APP_ENV_FILE}" ]; then
  set -a
  # shellcheck disable=SC1090
  . "${APP_ENV_FILE}"
  set +a
fi

map_prefixed_env() {
  prefixed_name="$1"
  target_name="$2"
  eval "prefixed_value=\${$prefixed_name:-}"
  eval "target_value=\${$target_name:-}"
  if [ -n "${prefixed_value}" ] && [ -z "${target_value}" ]; then
    export "${target_name}=${prefixed_value}"
  fi
}

map_prefixed_env APP_QUESTION_JSON_DIR QUESTION_JSON_DIR
map_prefixed_env APP_DATABASE_URL DATABASE_URL
map_prefixed_env APP_ENV APP_ENV
map_prefixed_env APP_ENFORCE_PRODUCTION_SAFETY ENFORCE_PRODUCTION_SAFETY
map_prefixed_env APP_BOOTSTRAP_SCHEMA BOOTSTRAP_SCHEMA
map_prefixed_env APP_RUN_DB_MIGRATIONS RUN_DB_MIGRATIONS
map_prefixed_env APP_MATERIAL_DIR MATERIAL_DIR
map_prefixed_env APP_CORS_ORIGINS CORS_ORIGINS
map_prefixed_env APP_AUTH_TOKEN_TTL_HOURS AUTH_TOKEN_TTL_HOURS
map_prefixed_env APP_AUTH_TOKEN_BYTES AUTH_TOKEN_BYTES
map_prefixed_env APP_AUTH_COOKIE_NAME AUTH_COOKIE_NAME
map_prefixed_env APP_AUTH_COOKIE_SECURE AUTH_COOKIE_SECURE
map_prefixed_env APP_AUTH_COOKIE_SAMESITE AUTH_COOKIE_SAMESITE
map_prefixed_env APP_AUTH_COOKIE_DOMAIN AUTH_COOKIE_DOMAIN
map_prefixed_env APP_PUBLIC_WEB_ORIGIN PUBLIC_WEB_ORIGIN
map_prefixed_env APP_LOG_LEVEL LOG_LEVEL
map_prefixed_env APP_LOG_JSON LOG_JSON
map_prefixed_env APP_SLOW_REQUEST_THRESHOLD_MS SLOW_REQUEST_THRESHOLD_MS
map_prefixed_env APP_TRUST_REQUEST_ID_HEADER TRUST_REQUEST_ID_HEADER
map_prefixed_env APP_RATE_LIMIT_ENABLED RATE_LIMIT_ENABLED
map_prefixed_env APP_RATE_LIMIT_PUBLIC_REQUESTS RATE_LIMIT_PUBLIC_REQUESTS
map_prefixed_env APP_RATE_LIMIT_PUBLIC_WINDOW_SECONDS RATE_LIMIT_PUBLIC_WINDOW_SECONDS
map_prefixed_env APP_RATE_LIMIT_AUTH_REQUESTS RATE_LIMIT_AUTH_REQUESTS
map_prefixed_env APP_RATE_LIMIT_AUTH_WINDOW_SECONDS RATE_LIMIT_AUTH_WINDOW_SECONDS
map_prefixed_env APP_RATE_LIMIT_ADMIN_REQUESTS RATE_LIMIT_ADMIN_REQUESTS
map_prefixed_env APP_RATE_LIMIT_ADMIN_WINDOW_SECONDS RATE_LIMIT_ADMIN_WINDOW_SECONDS
map_prefixed_env APP_RATE_LIMIT_CACHE_SIZE RATE_LIMIT_CACHE_SIZE
map_prefixed_env APP_ABUSE_SIGNAL_ENABLED ABUSE_SIGNAL_ENABLED
map_prefixed_env APP_ABUSE_SIGNAL_WINDOW_SECONDS ABUSE_SIGNAL_WINDOW_SECONDS
map_prefixed_env APP_ABUSE_DISTINCT_PATH_THRESHOLD ABUSE_DISTINCT_PATH_THRESHOLD
map_prefixed_env APP_ABUSE_RATE_LIMIT_BREACH_THRESHOLD ABUSE_RATE_LIMIT_BREACH_THRESHOLD
map_prefixed_env APP_ABUSE_SIGNAL_COOLDOWN_SECONDS ABUSE_SIGNAL_COOLDOWN_SECONDS
map_prefixed_env APP_GEMINI_ENABLE GEMINI_ENABLE
map_prefixed_env APP_GEMINI_API_KEY GEMINI_API_KEY
map_prefixed_env APP_GEMINI_MODEL GEMINI_MODEL
map_prefixed_env APP_GEMINI_TIMEOUT_SECONDS GEMINI_TIMEOUT_SECONDS
map_prefixed_env APP_GEMINI_TEMPERATURE GEMINI_TEMPERATURE
map_prefixed_env APP_GEMINI_MAX_OUTPUT_TOKENS GEMINI_MAX_OUTPUT_TOKENS
map_prefixed_env APP_GEMINI_SYSTEM_PROMPT GEMINI_SYSTEM_PROMPT
map_prefixed_env APP_GEMINI_MIN_RESPONSE_CHARS GEMINI_MIN_RESPONSE_CHARS
map_prefixed_env APP_GEMINI_RETRY_ON_SHORT GEMINI_RETRY_ON_SHORT
map_prefixed_env APP_GEMINI_CANDIDATE_COUNT GEMINI_CANDIDATE_COUNT

: "${QUESTION_JSON_DIR:=/questions}"
: "${DATABASE_URL:=postgresql+psycopg://sentinel:sentinel@postgres:5432/sentinel_quiz}"
: "${APP_ENV:=development}"
: "${ENFORCE_PRODUCTION_SAFETY:=true}"
: "${BOOTSTRAP_SCHEMA:=true}"
: "${RUN_DB_MIGRATIONS:=false}"
: "${MATERIAL_DIR:=/app/material}"
: "${AUTH_TOKEN_TTL_HOURS:=168}"
: "${AUTH_TOKEN_BYTES:=32}"
: "${AUTH_COOKIE_NAME:=sentinel_session}"
: "${AUTH_COOKIE_SECURE:=true}"
: "${AUTH_COOKIE_SAMESITE:=lax}"
: "${AUTH_COOKIE_DOMAIN:=}"
: "${APP_NGINX_HOST:=localhost}"
: "${LOG_LEVEL:=INFO}"
: "${LOG_JSON:=true}"
: "${SLOW_REQUEST_THRESHOLD_MS:=1200}"
: "${TRUST_REQUEST_ID_HEADER:=true}"
: "${RATE_LIMIT_ENABLED:=true}"
: "${RATE_LIMIT_PUBLIC_REQUESTS:=180}"
: "${RATE_LIMIT_PUBLIC_WINDOW_SECONDS:=60}"
: "${RATE_LIMIT_AUTH_REQUESTS:=40}"
: "${RATE_LIMIT_AUTH_WINDOW_SECONDS:=60}"
: "${RATE_LIMIT_ADMIN_REQUESTS:=60}"
: "${RATE_LIMIT_ADMIN_WINDOW_SECONDS:=60}"
: "${RATE_LIMIT_CACHE_SIZE:=50000}"
: "${ABUSE_SIGNAL_ENABLED:=true}"
: "${ABUSE_SIGNAL_WINDOW_SECONDS:=60}"
: "${ABUSE_DISTINCT_PATH_THRESHOLD:=30}"
: "${ABUSE_RATE_LIMIT_BREACH_THRESHOLD:=3}"
: "${ABUSE_SIGNAL_COOLDOWN_SECONDS:=300}"
: "${CORS_ORIGINS:=http://127.0.0.1:8000,http://localhost:8000,http://127.0.0.1:3000,http://localhost:3000}"
: "${GEMINI_ENABLE:=true}"
: "${GEMINI_MODEL:=gemini-1.5-flash}"
: "${GEMINI_TIMEOUT_SECONDS:=20}"
: "${GEMINI_TEMPERATURE:=0.2}"
: "${GEMINI_MAX_OUTPUT_TOKENS:=400}"
: "${GEMINI_MIN_RESPONSE_CHARS:=220}"
: "${GEMINI_RETRY_ON_SHORT:=true}"
: "${GEMINI_CANDIDATE_COUNT:=1}"

if [ -z "${PUBLIC_WEB_ORIGIN:-}" ]; then
  PUBLIC_WEB_ORIGIN="https://${APP_NGINX_HOST}"
fi

export QUESTION_JSON_DIR
export DATABASE_URL
export APP_ENV
export ENFORCE_PRODUCTION_SAFETY
export BOOTSTRAP_SCHEMA
export RUN_DB_MIGRATIONS
export MATERIAL_DIR
export AUTH_TOKEN_TTL_HOURS
export AUTH_TOKEN_BYTES
export AUTH_COOKIE_NAME
export AUTH_COOKIE_SECURE
export AUTH_COOKIE_SAMESITE
export AUTH_COOKIE_DOMAIN
export PUBLIC_WEB_ORIGIN
export LOG_LEVEL
export LOG_JSON
export SLOW_REQUEST_THRESHOLD_MS
export TRUST_REQUEST_ID_HEADER
export RATE_LIMIT_ENABLED
export RATE_LIMIT_PUBLIC_REQUESTS
export RATE_LIMIT_PUBLIC_WINDOW_SECONDS
export RATE_LIMIT_AUTH_REQUESTS
export RATE_LIMIT_AUTH_WINDOW_SECONDS
export RATE_LIMIT_ADMIN_REQUESTS
export RATE_LIMIT_ADMIN_WINDOW_SECONDS
export RATE_LIMIT_CACHE_SIZE
export ABUSE_SIGNAL_ENABLED
export ABUSE_SIGNAL_WINDOW_SECONDS
export ABUSE_DISTINCT_PATH_THRESHOLD
export ABUSE_RATE_LIMIT_BREACH_THRESHOLD
export ABUSE_SIGNAL_COOLDOWN_SECONDS
export CORS_ORIGINS
export GEMINI_ENABLE
export GEMINI_MODEL
export GEMINI_TIMEOUT_SECONDS
export GEMINI_TEMPERATURE
export GEMINI_MAX_OUTPUT_TOKENS
export GEMINI_MIN_RESPONSE_CHARS
export GEMINI_RETRY_ON_SHORT
export GEMINI_CANDIDATE_COUNT

if [ "${RUN_DB_MIGRATIONS}" = "true" ] || [ "${RUN_DB_MIGRATIONS}" = "1" ]; then
  alembic -c /app/alembic.ini upgrade head
fi

exec "$@"
