import type { MetadataRoute } from "next";

import { getMessages } from "@/lib/i18n";
import { getRequestLocale } from "@/lib/i18n/server";
import { THEME_CANVAS_COLORS } from "@/lib/theme/boot";

/**
 * Web app manifest (/manifest.webmanifest): makes Sentinel Quiz installable ("Install app" in
 * Edge/Chrome, "Add to Home Screen" on Android and iOS) and opens it standalone, without browser UI.
 *
 * Browsers fetch the manifest without cookies, so the locale comes from Accept-Language.
 * Icons are generated by scripts/generate-pwa-icons.mjs.
 */
export default async function manifest(): Promise<MetadataRoute.Manifest> {
  const { locale } = await getRequestLocale();
  const messages = getMessages(locale);
  const shortcutIcon = [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }];

  return {
    id: "/",
    name: messages.common.appName,
    short_name: messages.metadata.shortName,
    description: messages.metadata.description,
    lang: locale,
    dir: "ltr",
    // Guests can use the dashboard too (local progress), so the app always opens on it.
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    background_color: THEME_CANVAS_COLORS.light,
    theme_color: THEME_CANVAS_COLORS.light,
    categories: ["education", "productivity"],
    prefer_related_applications: false,
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" }
    ],
    // Long-press (Android) / right-click (desktop) on the installed app icon.
    shortcuts: [
      { name: messages.common.actions.newSession, url: "/start", icons: shortcutIcon },
      { name: messages.common.labels.review, url: "/review", icons: shortcutIcon },
      { name: messages.quizPlay.meta.entryTitle, short_name: messages.quizPlay.brand, url: "/j", icons: shortcutIcon },
      { name: messages.common.labels.history, url: "/history", icons: shortcutIcon }
    ]
  };
}
